### PR TITLE
Added possibility to unload modules and automatic unload when rerunning

### PR DESCRIPTION
**Pull request by Xartos**
Thanks for this great repo it has been very useful for me.

Although I have suggestions to some "quality of life" stuff to make it possible to run the script multiple times.
At least for me this makes it a bit easier if something goes wrong and you need to reapply the setup, it's nice to be able to just run the same command again instead of looking up the module ids and unloading them. And to be able to reset your setup after you're done using it.

### CODE REVIEW

**Comment by toadjaune** [comment]
This looks good to me, I assume that it still works fine even if the `modules_lists.txt` file doesn't exist, or if the corresonding devices don't exist anymore ?

**Comment by Xartos** [comment]
That is a very good point. Depending on how much modules you're loading/unload, it could definitely unload some modules it shouldn't.

But when you run this and load the modules it should add ID's that is bigger than what the autoloaded modules are for a static setup. If you then restart the system the ID's in this file shouldn't exist. Then again assuming a static setup.

But I could add a flag so that this feature is an opt-in feature rather than it always running and potentially causing havoc

**Comment by toadjaune** [comment]
Just had another idea : How about writing the `modules_lists.txt` to `/tmp` ? This way, it won't be persisted when rebooting.

Also, the README doesn't reflect the new opt-in behaviour.

I was also wondering if simply letting the user unload and reload themselves (for example with a one-liner such as `./pulse_unload.sh && ./pulse_setup.sh`) would be better ; it makes both implementation and understanding dead simple.

What do you think ?

**Comment by Xartos** [comment]
Yes and yes! I totally agree.
The scripts feel much cleaner and understandable now.

I also added some sanity checks for the unloading as well. I doubt it's super necessary but just to be sure.

**Comment by toadjaune** [comment]
That looks good, thanks a lot :)

**Pull request merged**
